In [1]:
import pandas as pd
import numpy as np
import seaborn as sns


In [2]:
data = pd.read_csv('hotel_bookings.csv')  #reading the data

In [3]:
# removing irrelevant attributes.

# a list of irrelevant attributes
irrelevant_attributes = ['arrival_date_year','arrival_date_month', 'arrival_date_week_number','arrival_date_day_of_month',
                        'children','babies', 'country', 'market_segment', 'previous_cancellations',
                        'previous_bookings_not_canceled', 'booking_changes', 'agent', 'company','days_in_waiting_list',
                        'required_car_parking_spaces','reservation_status_date']

for attribute in irrelevant_attributes:
    data.drop(attribute, axis = 1, inplace = True)

In [4]:
# The following code encodes categorical attributes in to binary. It uses a Panda function known as get_dummies()
# and drops the which converts data into binary. The attributes are dropped after conversion is made.


# encoding reservation status category and drop it after.
status = np.array(data.reservation_status)
Reservation_status = []
for value in status:
    if value == 'Canceled':
        Reservation_status.append(0)
    elif value == 'Check-Out':
        Reservation_status.append(1)
    elif value == 'No-Show':
        Reservation_status.append(2)
data['Reservation_status'] = Reservation_status
data.drop('reservation_status', axis = 1, inplace = True)

# encoding meal category
data = pd.concat([data, pd.get_dummies(data['meal'], prefix = 'meal_type')], axis = 1)
data.drop('meal', axis = 1, inplace = True)

# encoding distribution channel
data = pd.concat([data, pd.get_dummies(data['distribution_channel'], prefix = 'distr_channel')], axis = 1)
data.drop('distribution_channel', axis = 1, inplace = True)

# encoding deposit_type
data = pd.concat([data, pd.get_dummies(data['deposit_type'], prefix = 'deposit')], axis = 1)
data.drop('deposit_type', axis = 1, inplace = True)

# enocding customer_type
data = pd.concat([data, pd.get_dummies(data['customer_type'], prefix = 'cust_type')], axis = 1)
data.drop('customer_type', axis = 1, inplace = True)


In [5]:
data['total_of_special_requests'].unique()


array([0, 1, 3, 2, 4, 5])

In [6]:
# The following code combines two attributes -reserved_room_type and assigned_room_type together. These attributes
# are strongly related because when a customer reserves a prefered room, they may be able to get the room or not. 
# Therefore to combine these two attributes and still have their significance in the data, the code compares every
# value in the lists element wise. if the values are similar, 1 is appended in the list(prefered_room) meaning 
# that the customer got the room they requested and 0 otherwise.
# The new attribute(prefered_room) with binary values is merged with the dataframe
reserved_room = np.array(data.reserved_room_type)
assigned_room = np.array(data.assigned_room_type)
combined_room = list(zip(reserved_room, assigned_room))
prefered_room = []
for item in combined_room:
    if item[0] == item[1]:
        prefered_room.append(1)
    else:
        prefered_room.append(0)
        
# merge the attribute to the dataframe and drop attributes - reserved_room_type and assigned_room_type       
data['prefered_room'] = prefered_room 
data.drop('reserved_room_type', axis = 1, inplace = True)
data.drop('assigned_room_type', axis = 1, inplace = True)


In [7]:
data.head(7)

hotel  is_canceled  lead_time  stays_in_weekend_nights  \
0  Resort Hotel            0        342                        0   
1  Resort Hotel            0        737                        0   
2  Resort Hotel            0          7                        0   
3  Resort Hotel            0         13                        0   
4  Resort Hotel            0         14                        0   
5  Resort Hotel            0         14                        0   
6  Resort Hotel            0          0                        0   

   stays_in_week_nights  adults  is_repeated_guest    adr  \
0                     0       2                  0    0.0   
1                     0       2                  0    0.0   
2                     1       1                  0   75.0   
3                     1       1                  0   75.0   
4                     2       2                  0   98.0   
5                     2       2                  0   98.0   
6                     2       2                  0  107.0   

   total_of_special_requests  Reservation_status  ...  distr_channel_TA/TO  \
0                          0                   1  ...                    0   
1                          0                   1  ...                    0   
2                          0                   1  ...                    0   
3                          0                   1  ...                    0   
4                          1                   1  ...                    1   
5                          1                   1  ...                    1   
6                          0                   1  ...                    0   

   distr_channel_Undefined  deposit_No Deposit  deposit_Non Refund  \
0                        0                   1                   0   
1                        0                   1                   0   
2                        0                   1                   0   
3                        0                   1                   0   
4                        0                   1                   0   
5                        0                   1                   0   
6                        0                   1                   0   

   deposit_Refundable  cust_type_Contract  cust_type_Group  \
0                   0                   0                0   
1                   0                   0                0   
2                   0                   0                0   
3                   0                   0                0   
4                   0                   0                0   
5                   0                   0                0   
6                   0                   0                0   

   cust_type_Transient  cust_type_Transient-Party  prefered_room  
0                    1                          0              1  
1                    1                          0              1  
2                    1                          0              0  
3                    1                          0              1  
4                    1                          0              1  
5                    1                          0              1  
6                    1                          0              1  

[7 rows x 28 columns]

In [8]:
# Extracting Resort Hotel data
resort_data = data[data["hotel"] == "Resort Hotel"]
resort_data.columns

Index(['hotel', 'is_canceled', 'lead_time', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'is_repeated_guest', 'adr',
       'total_of_special_requests', 'Reservation_status', 'meal_type_BB',
       'meal_type_FB', 'meal_type_HB', 'meal_type_SC', 'meal_type_Undefined',
       'distr_channel_Corporate', 'distr_channel_Direct', 'distr_channel_GDS',
       'distr_channel_TA/TO', 'distr_channel_Undefined', 'deposit_No Deposit',
       'deposit_Non Refund', 'deposit_Refundable', 'cust_type_Contract',
       'cust_type_Group', 'cust_type_Transient', 'cust_type_Transient-Party',
       'prefered_room'],
      dtype='object')

In [9]:
# predict the average daily rate and anaylse what factors affect it

# # standardizing the data (Resort data) 
from sklearn.preprocessing import StandardScaler, MinMaxScaler 
scaler = StandardScaler()
scaler2 = MinMaxScaler()
X = resort_data.drop(['hotel', 'adr'], axis = 1)
for attribute in X.columns:
    X[attribute] = scaler.fit_transform(np.array(X[attribute]).reshape(-1,1))

# target variable. average daily rate    
Y = resort_data.adr

# split the data into train and test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

# Using the linear classifier to predict the average daily rate
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures 

regressor = LinearRegression()
regressor.fit(X_train, Y_train)

# predicting the average daily rate
y_pred = regressor.predict(X_test)

# These coefficients could help us know which variables are highly correlated with 
# the average daily rate
coefficient_df = pd.DataFrame(regressor.coef_, X.columns, columns = ['coefficients'])
print(coefficient_df)

print(r2_score(Y_test, y_pred))

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by Stand

                           coefficients
is_canceled                7.046421e-01
lead_time                 -5.237547e-01
stays_in_weekend_nights   -1.133074e+00
stays_in_week_nights       3.259250e+00
adults                     7.208646e+00
is_repeated_guest         -3.393437e+00
total_of_special_requests  8.534869e+00
Reservation_status        -4.680830e+00
meal_type_BB               5.161743e+13
meal_type_FB               1.617795e+13
meal_type_HB               4.769452e+13
meal_type_SC               5.509936e+12
meal_type_Undefined        2.003735e+13
distr_channel_Corporate   -4.053446e+12
distr_channel_Direct      -5.881521e+12
distr_channel_GDS         -6.536225e+13
distr_channel_TA/TO       -6.633273e+12
distr_channel_Undefined   -7.397690e+10
deposit_No Deposit        -2.169595e+14
deposit_Non Refund        -2.089052e+14
deposit_Refundable        -6.126438e+13
cust_type_Contract         4.638488e+14
cust_type_Group            1.890671e+14
cust_type_Transient        9.704085e+14


In [10]:

# predicting the reservation status of customers who booked resort hotels

# Standardizing target data
from sklearn.preprocessing import StandardScaler, MinMaxScaler 
scaler = StandardScaler()
X2 = resort_data.drop(['hotel','Reservation_status','is_canceled'], axis = 1)
for attribute in X2.columns:
    X2[attribute] = scaler.fit_transform(np.array(X2[attribute]).reshape(-1,1))
    
# target variable. reservation status
Y2 = resort_data['Reservation_status']


# Using KNN classifier to predict the reservation status

# split the data
X2_train, X2_test, Y2_train, Y2_test = train_test_split(X2, Y2, test_size = 0.25, random_state = 0)

from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X2_train, Y2_train)
y2_pred = knn_classifier.predict(X2_test)



/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by Stand

In [11]:
# Evaluating the model.Print the accuracy and confusion matrix
from sklearn import metrics
print(metrics.accuracy_score(Y2_test, y2_pred))
print(metrics.confusion_matrix(Y2_test, y2_pred))


0.8045931103344982
[[1568 1103    0]
 [ 784 6482    0]
 [   8   62    8]]


In [12]:
# Using support vector machine (svm) to predict the reservation status
from sklearn.svm import SVC
svc_classifier = SVC(kernel = 'linear')
svc_classifier.fit(X2_train, Y2_train)
y3_predSVC = svc_classifier.predict(X2_test)

print(metrics.accuracy_score(Y2_test, y3_predSVC))
print(metrics.confusion_matrix(Y2_test, y3_predSVC))

0.7656515227159261
[[ 419 2252    0]
 [  17 7249    0]
 [   7   71    0]]


In [13]:
# using random forest classification to predict the reservation status
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier()
rf_classifier.fit(X2_train, Y2_train)
y_predrf = rf_classifier.predict(X2_test)
print(metrics.accuracy_score(Y2_test, y_predrf))
print(metrics.confusion_matrix(Y2_test, y_predrf))

/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.818172740888667
[[1782  887    2]
 [ 857 6401    8]
 [   7   60   11]]


In [14]:
# comparing the perfomance of each classifier using cross validation
from sklearn.model_selection import cross_val_score
classifiers = [knn_classifier, svc_classifier, rf_classifier] # a list of classfiers
for i in classifiers:
    print(cross_val_score(i, X2, Y2, cv = 10).mean())


0.7039166734789456
0.756591613538449
0.6938804542873581


In [15]:
# Analysing the likelihood for customers to cancel their booking for resort hotels

# target variable canceled = 1, not canceled = 0
y = resort_data.is_canceled

# Scaling dependent variables
scaler2 = StandardScaler()
x = resort_data.drop(['is_canceled','hotel', 'Reservation_status'], axis = 1)
for attribute in x.columns:
    x[attribute] = scaler2.fit_transform(np.array(x[attribute]).reshape(-1,1))
    


# split the data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)

# use logistic regression to predict binomial outcomes

from sklearn.linear_model import LogisticRegression #importing Logistic regression
log_regressor = LogisticRegression()

log_regressor.fit(x_train,y_train) #fitting the model to the data

y_pred = log_regressor.predict(x_test) # predicting x test data
print("confusion matrix and accuracy for logistic regression")
print(metrics.confusion_matrix(y_test, y_pred)) #confusion matrix

print(metrics.accuracy_score(y_test, y_pred))


# using random forest to predict the likelihood for customers to cancel
# their booking
random_forest_regressor = RandomForestClassifier()
random_forest_regressor.fit(x_train, y_train) 
rf_ypred = random_forest_regressor.predict(x_test)


/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by Stand

confusion matrix and accuracy for logistic regression
[[6890  302]
 [1942  881]]
0.7759360958562157


/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [16]:
print("confusion matrix and accuracy for random forest classifier")
print(metrics.confusion_matrix(y_test, rf_ypred)) #confusion matrix
print()
print(metrics.accuracy_score(y_test, rf_ypred)) #accuracy


confusion matrix and accuracy for random forest classifier
[[6603  589]
 [1170 1653]]

0.8243634548177733


In [17]:
# using cross validation to evluate the logistic regression and 
# random classification model
from sklearn.model_selection import cross_val_score
print(cross_val_score(log_regressor, x, y, cv= 10).mean())
print(cross_val_score(random_forest_regressor, x, y, cv=10).mean())

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  Futur

0.737667187928283
0.7079097452941135


In [18]:
# Analysis on the likelihood for a hotel to have a repeated customer

# target variable variable repeated guest = 1, not a repeated guest = 0
y_repeated_customer = resort_data.is_repeated_guest

# independent variable
x_repeated_customer = resort_data.drop(['hotel', 'is_repeated_guest'], axis = 1)


# split the data 
X_training, X_testing, y_training, y_testing = train_test_split(x_repeated_customer,
                                                             y_repeated_customer, test_size = 0.25)

# use logistic regression to predict wheather a customer will be a repeated guest

from sklearn.linear_model import LogisticRegression #importing Logistic regression
log_regressor2 = LogisticRegression()

log_regressor2.fit(X_training,y_training) #fitting the model to the data

y_prediction = log_regressor2.predict(X_testing) # predicting x test data

                                                            

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [19]:
print("confusion matrix and accuracy for logistic regression")
print(metrics.confusion_matrix(y_testing, y_prediction)) #confusion matrix
print()
print(metrics.accuracy_score(y_testing, y_prediction))
print(metrics.precision_score(y_testing, y_prediction, average = 'micro'))
print(metrics.recall_score(y_testing, y_prediction, average = 'micro'))


confusion matrix and accuracy for logistic regression
[[9569   16]
 [ 415   15]]

0.9569645531702446
0.9569645531702446
0.9569645531702446


In [20]:
# using random forest to predict repeated customer 
random_forest_regressor2 = RandomForestClassifier()
random_forest_regressor2.fit(X_training, y_training) 
rf_yprediction = random_forest_regressor2.predict(X_testing)
print("confusion matrix and accuracy for random forest classifier")
print(metrics.confusion_matrix(y_testing, rf_yprediction)) #confusion matrix
print()
print(metrics.accuracy_score(y_testing, rf_yprediction))
print(metrics.precision_score(y_testing, y_prediction, average = 'micro'))
print(metrics.recall_score(y_testing, y_prediction, average = 'micro'))


/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


confusion matrix and accuracy for random forest classifier
[[9463  122]
 [ 313  117]]

0.9565651522715926
0.9569645531702446
0.9569645531702446


In [21]:
# using cross validation to evluate the logistic regression and 
# random classification model
print(cross_val_score(log_regressor2, x, y, cv= 10).mean())
print(cross_val_score(random_forest_regressor2, x_repeated_customer, y_repeated_customer, cv=10).mean())

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  Futur

0.737667187928283
0.9430596977617413


In [22]:
# if the total number of special requests is greater than 0, append 1 to has_special_request list otherwise
# append 0.
special_requests = np.array(resort_data.total_of_special_requests)
has_special_request = []
for i in special_requests:
    if i == 0:
        has_special_request.append(0)
    else:
        has_special_request.append(1)

# adding has_special_request attribute to the datafrae and drop the original attribute.
resort_data['has_special_request'] = has_special_request
resort_data.drop('total_of_special_requests', axis=1)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':


hotel  is_canceled  lead_time  stays_in_weekend_nights  \
0      Resort Hotel            0        342                        0   
1      Resort Hotel            0        737                        0   
2      Resort Hotel            0          7                        0   
3      Resort Hotel            0         13                        0   
4      Resort Hotel            0         14                        0   
5      Resort Hotel            0         14                        0   
6      Resort Hotel            0          0                        0   
7      Resort Hotel            0          9                        0   
8      Resort Hotel            1         85                        0   
9      Resort Hotel            1         75                        0   
10     Resort Hotel            1         23                        0   
11     Resort Hotel            0         35                        0   
12     Resort Hotel            0         68                        0   
13     Resort Hotel            0         18                        0   
14     Resort Hotel            0         37                        0   
15     Resort Hotel            0         68                        0   
16     Resort Hotel            0         37                        0   
17     Resort Hotel            0         12                        0   
18     Resort Hotel            0          0                        0   
19     Resort Hotel            0          7                        0   
20     Resort Hotel            0         37                        1   
21     Resort Hotel            0         72                        2   
22     Resort Hotel            0         72                        2   
23     Resort Hotel            0         72                        2   
24     Resort Hotel            0        127                        2   
25     Resort Hotel            0         78                        2   
26     Resort Hotel            0         48                        2   
27     Resort Hotel            1         60                        2   
28     Resort Hotel            0         77                        2   
29     Resort Hotel            0         99                        2   
...             ...          ...        ...                      ...   
40030  Resort Hotel            0        135                        2   
40031  Resort Hotel            0        301                        2   
40032  Resort Hotel            0         21                        2   
40033  Resort Hotel            0        379                        4   
40034  Resort Hotel            0        279                        2   
40035  Resort Hotel            0         21                        2   
40036  Resort Hotel            0        279                        2   
40037  Resort Hotel            0        379                        4   
40038  Resort Hotel            0        191                        2   
40039  Resort Hotel            0        108                        2   
40040  Resort Hotel            0        194                        2   
40041  Resort Hotel            0        227                        2   
40042  Resort Hotel            0        210                        2   
40043  Resort Hotel            0        227                        2   
40044  Resort Hotel            0        270                        4   
40045  Resort Hotel            0        210                        4   
40046  Resort Hotel            0        208                        4   
40047  Resort Hotel            0        214                        2   
40048  Resort Hotel            0        239                        2   
40049  Resort Hotel            0        217                        2   
40050  Resort Hotel            0        173                        4   
40051  Resort Hotel            0        264                        4   
40052  Resort Hotel            0        207                        4   
40053  Resort Hotel            0        269           

In [23]:
# predicting the likelihood of a customer to have requests

# Standardizing target data
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()
x4 = resort_data.drop(['hotel','has_special_request'], axis = 1)
# for attribute in x4.columns:
#     x4[attribute] = scaler.fit_transform(np.array(x4[attribute]).reshape(-1,1))
    
# target variable. has_special_request
y4 = resort_data['has_special_request']


# Using knn to predict special requests

# split the data
x4_train, x4_test, y4_train, y4_test = train_test_split(x4, y4, test_size = 0.25, random_state = 0)

#using KNN classifier
knn_regressor = KNeighborsClassifier()
knn_regressor.fit(x4_train, y4_train)
y4_pred = knn_regressor.predict(x4_test)


In [24]:
# Evaluating the model.Print the accuracy and confusion matrix
from sklearn import metrics
print(metrics.accuracy_score(y4_test, y4_pred))
print(metrics.confusion_matrix(y4_test, y4_pred))

0.7642536195706441
[[4376 1249]
 [1112 3278]]
